### PR TITLE
Fix game_version variable taint (Fixes #83)

### LINKED ISSUE #83: game_version variable taint
When uploading to WowInterface, the game_version varaible gets tained here: https://github.com/BigWigsMods/packager/blob/master/release.sh#L2306

Which when uploading to wago, causes it to use the tainted variable as a release, which wago then marks as invalid.

Logs:

```
Uploading <Addon>-bc.zip (2.5.1 release) to https://wow.curseforge.com/projects/<id>
Success!

Uploading <Addon>-bc.zip (2.05.1) to https://www.wowinterface.com/downloads/info<id>
Success!

Uploading <Addon>-bc.zip (2.05.1 release) to Wago
Error! (422)
{"message":"The given data was invalid.","errors":{"supported_bc_patch":["The selected supported bc patch is invalid."]}}
```

### PR DESCRIPTION
**Pull request by QartemisT**

### CODE REVIEW

File: release.sh [hunk 1]
```diff
@@ -2304,21 +2304,22 @@ if [ -z "$skip_zipfile" ]; then
 	fi
 
 	if [ -n "$upload_wowinterface" ]; then
+		wowi_game_version=game_version
 		_wowi_versions=$( curl -s -H "x-api-token: $wowi_token" https://api.wowinterface.com/addons/compatible.json )
 		if [ -n "$_wowi_versions" ]; then
-			game_version=$( echo "$_wowi_versions" | jq -r '.[] | select(.interface == "'"$toc_version"'" and .default == true) | .id' 2>/dev/null )
-			if [ -z "$game_version" ]; then
-				game_version=$( echo "$_wowi_versions" | jq -r 'map(select(.interface == "'"$toc_version"'"))[0] | .id // empty' 2>/dev/null )
+			_wowi_game_version=$( echo "$_wowi_versions" | jq -r '.[] | select(.interface == "'"$toc_version"'" and .default == true) | .id' 2>/dev/null )
```
Comment (nebularg) [inline release.sh:2310]: _wowi_game_version -> wowi_game_version

**Review by nebularg — CHANGES_REQUESTED** [review]
Ah thanks, I had forgotten this was an issue when Wago was added

**Review by nebularg — APPROVED** [review]
